#ifndef	_RELOCATE_ARM_MSG_DOT_H
#define	_RELOCATE_ARM_MSG_DOT_H

#include <sgsmsg.h>	/* Msg typedef */

#ifndef	__lint

#define	MSG_SGS_LOCAL_ARRAY	__sgs_msg_libconv_relocate_arm

extern	const char	__sgs_msg_libconv_relocate_arm[];

#define	MSG_ORIG_STRTAB(_x, _s)	&_s[_x]

#define	MSG_ORIG(x)	MSG_ORIG_STRTAB(x, __sgs_msg_libconv_relocate_arm)

extern	const char *	_sgs_msg_libconv_relocate_arm(Msg);

#define	MSG_INTL(x)	_sgs_msg_libconv_relocate_arm(x)


#define	MSG_R_ARM_NONE	1
#define	MSG_R_ARM_NONE_SIZE	10

#define	MSG_R_ARM_PC24	12
#define	MSG_R_ARM_PC24_SIZE	10

#define	MSG_R_ARM_ABS32	23
#define	MSG_R_ARM_ABS32_SIZE	11

#define	MSG_R_ARM_REL32	35
#define	MSG_R_ARM_REL32_SIZE	11

#define	MSG_R_ARM_LDR_PC_G0	47
#define	MSG_R_ARM_LDR_PC_G0_SIZE	15

#define	MSG_R_ARM_ABS16	63
#define	MSG_R_ARM_ABS16_SIZE	11

#define	MSG_R_ARM_ABS12	75
#define	MSG_R_ARM_ABS12_SIZE	11

#define	MSG_R_ARM_THM_ABS5	87
#define	MSG_R_ARM_THM_ABS5_SIZE	14

#define	MSG_R_ARM_ABS8	102
#define	MSG_R_ARM_ABS8_SIZE	10

#define	MSG_R_ARM_SBREL32	113
#define	MSG_R_ARM_SBREL32_SIZE	13

#define	MSG_R_ARM_THM_CALL	127
#define	MSG_R_ARM_THM_CALL_SIZE	14

#define	MSG_R_ARM_THM_PC8	142
#define	MSG_R_ARM_THM_PC8_SIZE	13

#define	MSG_R_ARM_BREL_ADJ	156
#define	MSG_R_ARM_BREL_ADJ_SIZE	14

#define	MSG_R_ARM_TLS_DESC	171
#define	MSG_R_ARM_TLS_DESC_SIZE	14

#define	MSG_R_ARM_THM_SWI8	186
#define	MSG_R_ARM_THM_SWI8_SIZE	14

#define	MSG_R_ARM_XPC25	201
#define	MSG_R_ARM_XPC25_SIZE	11

#define	MSG_R_ARM_THM_XPC22	213
#define	MSG_R_ARM_THM_XPC22_SIZE	15

#define	MSG_R_ARM_TLS_DTPMOD32	229
#define	MSG_R_ARM_TLS_DTPMOD32_SIZE	18

#define	MSG_R_ARM_TLS_DTOFF32	248
#define	MSG_R_ARM_TLS_DTOFF32_SIZE	17

#define	MSG_R_ARM_TLS_TPOFF32	266
#define	MSG_R_ARM_TLS_TPOFF32_SIZE	17

#define	MSG_R_ARM_COPY	284
#define	MSG_R_ARM_COPY_SIZE	10

#define	MSG_R_ARM_GLOB_DAT	295
#define	MSG_R_ARM_GLOB_DAT_SIZE	14

#define	MSG_R_ARM_JUMP_SLOT	310
#define	MSG_R_ARM_JUMP_SLOT_SIZE	15

#define	MSG_R_ARM_RELATIVE	326
#define	MSG_R_ARM_RELATIVE_SIZE	14

#define	MSG_R_ARM_GOTOFF32	341
#define	MSG_R_ARM_GOTOFF32_SIZE	14

#define	MSG_R_ARM_BASE_PREL	356
#define	MSG_R_ARM_BASE_PREL_SIZE	15

#define	MSG_R_ARM_GOT_BREL	372
#define	MSG_R_ARM_GOT_BREL_SIZE	14

#define	MSG_R_ARM_PLT32	387
#define	MSG_R_ARM_PLT32_SIZE	11

#define	MSG_R_ARM_CALL	399
#define	MSG_R_ARM_CALL_SIZE	10

#define	MSG_R_ARM_JUMP24	410
#define	MSG_R_ARM_JUMP24_SIZE	12

#define	MSG_R_ARM_THM_JUMP24	423
#define	MSG_R_ARM_THM_JUMP24_SIZE	16

#define	MSG_R_ARM_BASE_ABS	440
#define	MSG_R_ARM_BASE_ABS_SIZE	14

#define	MSG_R_ARM_ALU_PCREL_7_0	455
#define	MSG_R_ARM_ALU_PCREL_7_0_SIZE	19

#define	MSG_R_ARM_ALU_PCREL_15_8	475
#define	MSG_R_ARM_ALU_PCREL_15_8_SIZE	20

#define	MSG_R_ARM_ALU_PCREL_23_15	496
#define	MSG_R_ARM_ALU_PCREL_23_15_SIZE	21

#define	MSG_R_ARM_LDR_SBREL_11_0_NC	518
#define	MSG_R_ARM_LDR_SBREL_11_0_NC_SIZE	23

#define	MSG_R_ARM_ALU_SBREL_19_12_NC	542
#define	MSG_R_ARM_ALU_SBREL_19_12_NC_SIZE	24

#define	MSG_R_ARM_ALU_SBREL_27_20_CK	567
#define	MSG_R_ARM_ALU_SBREL_27_20_CK_SIZE	24

#define	MSG_R_ARM_TARGET1	592
#define	MSG_R_ARM_TARGET1_SIZE	13

#define	MSG_R_ARM_SBREL31	606
#define	MSG_R_ARM_SBREL31_SIZE	13

#define	MSG_R_ARM_V4BX	620
#define	MSG_R_ARM_V4BX_SIZE	10

#define	MSG_R_ARM_TARGET2	631
#define	MSG_R_ARM_TARGET2_SIZE	13

#define	MSG_R_ARM_PREL31	645
#define	MSG_R_ARM_PREL31_SIZE	12

#define	MSG_R_ARM_MOVW_ABS_NC	658
#define	MSG_R_ARM_MOVW_ABS_NC_SIZE	17

#define	MSG_R_ARM_MOVT_ABS	676
#define	MSG_R_ARM_MOVT_ABS_SIZE	14

#define	MSG_R_ARM_MOVW_PREL_NC	691
#define	MSG_R_ARM_MOVW_PREL_NC_SIZE	18

#define	MSG_R_ARM_MOVT_PREL	710
#define	MSG_R_ARM_MOVT_PREL_SIZE	15

#define	MSG_R_ARM_THM_MOVW_ABS_NC	726
#define	MSG_R_ARM_THM_MOVW_ABS_NC_SIZE	21

#define	MSG_R_ARM_THM_MOVT_ABS	748
#define	MSG_R_ARM_THM_MOVT_ABS_SIZE	18

#define	MSG_R_ARM_THM_MOVW_PREL_NC	767
#define	MSG_R_ARM_THM_MOVW_PREL_NC_SIZE	22

#define	MSG_R_ARM_THM_MOVT_PREL	790
#define	MSG_R_ARM_THM_MOVT_PREL_SIZE	19

#define	MSG_R_ARM_THM_JUMP19	810
#define	MSG_R_ARM_THM_JUMP19_SIZE	16

#define	MSG_R_ARM_THM_JUMP6	827
#define	MSG_R_ARM_THM_JUMP6_SIZE	15

#define	MSG_R_ARM_THM_ALU_PREL_11_0	843
#define	MSG_R_ARM_THM_ALU_PREL_11_0_SIZE	23

#define	MSG_R_ARM_THM_PC12	867
#define	MSG_R_ARM_THM_PC12_SIZE	14

#define	MSG_R_ARM_ABS32_NOI	882
#define	MSG_R_ARM_ABS32_NOI_SIZE	15

#define	MSG_R_ARM_REL32_NOI	898
#define	MSG_R_ARM_REL32_NOI_SIZE	15

#define	MSG_R_ARM_ALU_PC_G0_NC	914
#define	MSG_R_ARM_ALU_PC_G0_NC_SIZE	18

#define	MSG_R_ARM_ALU_PC_G0	933
#define	MSG_R_ARM_ALU_PC_G0_SIZE	15

#define	MSG_R_ARM_ALU_PC_G1_NC	949
#define	MSG_R_ARM_ALU_PC_G1_NC_SIZE	18

#define	MSG_R_ARM_ALU_PC_G1	968
#define	MSG_R_ARM_ALU_PC_G1_SIZE	15

#define	MSG_R_ARM_ALU_PC_G2	984
#define	MSG_R_ARM_ALU_PC_G2_SIZE	15

#define	MSG_R_ARM_LDR_PC_G1	1000
#define	MSG_R_ARM_LDR_PC_G1_SIZE	15

#define	MSG_R_ARM_LDR_PC_G2	1016
#define	MSG_R_ARM_LDR_PC_G2_SIZE	15

#define	MSG_R_ARM_LDRS_PC_G0	1032
#define	MSG_R_ARM_LDRS_PC_G0_SIZE	16

#define	MSG_R_ARM_LDRS_PC_G1	1049
#define	MSG_R_ARM_LDRS_PC_G1_SIZE	16

#define	MSG_R_ARM_LDRS_PC_G2	1066
#define	MSG_R_ARM_LDRS_PC_G2_SIZE	16

#define	MSG_R_ARM_LDC_PC_G0	1083
#define	MSG_R_ARM_LDC_PC_G0_SIZE	15

#define	MSG_R_ARM_LDC_PC_G1	1099
#define	MSG_R_ARM_LDC_PC_G1_SIZE	15

#define	MSG_R_ARM_LDC_PC_G2	1115
#define	MSG_R_ARM_LDC_PC_G2_SIZE	15

#define	MSG_R_ARM_ALU_SB_G0_NC	1131
#define	MSG_R_ARM_ALU_SB_G0_NC_SIZE	18

#define	MSG_R_ARM_ALU_SB_G0	1150
#define	MSG_R_ARM_ALU_SB_G0_SIZE	15

#define	MSG_R_ARM_ALU_SB_G1_NC	1166
#define	MSG_R_ARM_ALU_SB_G1_NC_SIZE	18

#define	MSG_R_ARM_ALU_SB_G1	1185
#define	MSG_R_ARM_ALU_SB_G1_SIZE	15

#define	MSG_R_ARM_ALU_SB_G2	1201
#define	MSG_R_ARM_ALU_SB_G2_SIZE	15

#define	MSG_R_ARM_LDR_SB_G0	1217
#define	MSG_R_ARM_LDR_SB_G0_SIZE	15

#define	MSG_R_ARM_LDR_SB_G1	1233
#define	MSG_R_ARM_LDR_SB_G1_SIZE	15

#define	MSG_R_ARM_LDR_SB_G2	1249
#define	MSG_R_ARM_LDR_SB_G2_SIZE	15

#define	MSG_R_ARM_LDRS_SB_G0	1265
#define	MSG_R_ARM_LDRS_SB_G0_SIZE	16

#define	MSG_R_ARM_LDRS_SB_G1	1282
#define	MSG_R_ARM_LDRS_SB_G1_SIZE	16

#define	MSG_R_ARM_LDRS_SB_G2	1299
#define	MSG_R_ARM_LDRS_SB_G2_SIZE	16

#define	MSG_R_ARM_LDC_SB_G0	1316
#define	MSG_R_ARM_LDC_SB_G0_SIZE	15

#define	MSG_R_ARM_LDC_SB_G1	1332
#define	MSG_R_ARM_LDC_SB_G1_SIZE	15

#define	MSG_R_ARM_LDC_SB_G2	1348
#define	MSG_R_ARM_LDC_SB_G2_SIZE	15

#define	MSG_R_ARM_MOVW_BREL_NC	1364
#define	MSG_R_ARM_MOVW_BREL_NC_SIZE	18

#define	MSG_R_ARM_MOVT_BREL	1383
#define	MSG_R_ARM_MOVT_BREL_SIZE	15

#define	MSG_R_ARM_MOVW_BREL	1399
#define	MSG_R_ARM_MOVW_BREL_SIZE	15

#define	MSG_R_ARM_THM_MOVW_BREL_NC	1415
#define	MSG_R_ARM_THM_MOVW_BREL_NC_SIZE	22

#define	MSG_R_ARM_THM_MOVT_BREL	1438
#define	MSG_R_ARM_THM_MOVT_BREL_SIZE	19

#define	MSG_R_ARM_THM_MOVW_BREL	1458
#define	MSG_R_ARM_THM_MOVW_BREL_SIZE	19

#define	MSG_R_ARM_TLS_GOTDESC	1478
#define	MSG_R_ARM_TLS_GOTDESC_SIZE	17

#define	MSG_R_ARM_TLS_CALL	1496
#define	MSG_R_ARM_TLS_CALL_SIZE	14

#define	MSG_R_ARM_TLS_DESCSEQ	1511
#define	MSG_R_ARM_TLS_DESCSEQ_SIZE	17

#define	MSG_R_ARM_THM_TLS_CALL	1529
#define	MSG_R_ARM_THM_TLS_CALL_SIZE	18

#define	MSG_R_ARM_PLT32_ABS	1548
#define	MSG_R_ARM_PLT32_ABS_SIZE	15

#define	MSG_R_ARM_GOT_ABS	1564
#define	MSG_R_ARM_GOT_ABS_SIZE	13

#define	MSG_R_ARM_GOT_PREL	1578
#define	MSG_R_ARM_GOT_PREL_SIZE	14

#define	MSG_R_ARM_GOT_BREL12	1593
#define	MSG_R_ARM_GOT_BREL12_SIZE	16

#define	MSG_R_ARM_GOTOFF12	1610
#define	MSG_R_ARM_GOTOFF12_SIZE	14

#define	MSG_R_ARM_GOTRELAX	1625
#define	MSG_R_ARM_GOTRELAX_SIZE	14

#define	MSG_R_ARM_GNU_VTENTRY	1640
#define	MSG_R_ARM_GNU_VTENTRY_SIZE	17

#define	MSG_R_ARM_GNU_VTINHERIT	1658
#define	MSG_R_ARM_GNU_VTINHERIT_SIZE	19

#define	MSG_R_ARM_THM_JUMP11	1678
#define	MSG_R_ARM_THM_JUMP11_SIZE	16

#define	MSG_R_ARM_THM_JUMP8	1695
#define	MSG_R_ARM_THM_JUMP8_SIZE	15

#define	MSG_R_ARM_TLS_GD32	1711
#define	MSG_R_ARM_TLS_GD32_SIZE	14

#define	MSG_R_ARM_TLS_LDM32	1726
#define	MSG_R_ARM_TLS_LDM32_SIZE	15

#define	MSG_R_ARM_TLS_LDO32	1742
#define	MSG_R_ARM_TLS_LDO32_SIZE	15

#define	MSG_R_ARM_TLS_IE32	1758
#define	MSG_R_ARM_TLS_IE32_SIZE	14

#define	MSG_R_ARM_TLS_LE32	1773
#define	MSG_R_ARM_TLS_LE32_SIZE	14

#define	MSG_R_ARM_TLS_LDO12	1788
#define	MSG_R_ARM_TLS_LDO12_SIZE	15

#define	MSG_R_ARM_TLS_LE12	1804
#define	MSG_R_ARM_TLS_LE12_SIZE	14

#define	MSG_R_ARM_TLS_IE12GP	1819
#define	MSG_R_ARM_TLS_IE12GP_SIZE	16

#define	MSG_R_ARM_PRIVATE_0	1836
#define	MSG_R_ARM_PRIVATE_0_SIZE	15

#define	MSG_R_ARM_PRIVATE_1	1852
#define	MSG_R_ARM_PRIVATE_1_SIZE	15

#define	MSG_R_ARM_PRIVATE_2	1868
#define	MSG_R_ARM_PRIVATE_2_SIZE	15

#define	MSG_R_ARM_PRIVATE_3	1884
#define	MSG_R_ARM_PRIVATE_3_SIZE	15

#define	MSG_R_ARM_PRIVATE_4	1900
#define	MSG_R_ARM_PRIVATE_4_SIZE	15

#define	MSG_R_ARM_PRIVATE_5	1916
#define	MSG_R_ARM_PRIVATE_5_SIZE	15

#define	MSG_R_ARM_PRIVATE_6	1932
#define	MSG_R_ARM_PRIVATE_6_SIZE	15

#define	MSG_R_ARM_PRIVATE_7	1948
#define	MSG_R_ARM_PRIVATE_7_SIZE	15

#define	MSG_R_ARM_PRIVATE_8	1964
#define	MSG_R_ARM_PRIVATE_8_SIZE	15

#define	MSG_R_ARM_PRIVATE_9	1980
#define	MSG_R_ARM_PRIVATE_9_SIZE	15

#define	MSG_R_ARM_PRIVATE_10	1996
#define	MSG_R_ARM_PRIVATE_10_SIZE	16

#define	MSG_R_ARM_PRIVATE_11	2013
#define	MSG_R_ARM_PRIVATE_11_SIZE	16

#define	MSG_R_ARM_PRIVATE_12	2030
#define	MSG_R_ARM_PRIVATE_12_SIZE	16

#define	MSG_R_ARM_PRIVATE_13	2047
#define	MSG_R_ARM_PRIVATE_13_SIZE	16

#define	MSG_R_ARM_PRIVATE_14	2064
#define	MSG_R_ARM_PRIVATE_14_SIZE	16

#define	MSG_R_ARM_PRIVATE_15	2081
#define	MSG_R_ARM_PRIVATE_15_SIZE	16

#define	MSG_R_ARM_ME_TOO	2098
#define	MSG_R_ARM_ME_TOO_SIZE	12

#define	MSG_R_ARM_THM_TLS_DESCSEQ16	2111
#define	MSG_R_ARM_THM_TLS_DESCSEQ16_SIZE	23

#define	MSG_R_ARM_THM_TLS_DESCSEQ32	2135
#define	MSG_R_ARM_THM_TLS_DESCSEQ32_SIZE	23

#define	MSG_R_ARM_THM_GOT_BREL12	2159
#define	MSG_R_ARM_THM_GOT_BREL12_SIZE	20

#define	MSG_R_ARM_IRELATIVE	2180
#define	MSG_R_ARM_IRELATIVE_SIZE	15

#else	/* __lint */

extern	const char *	_sgs_msg_libconv_relocate_arm(Msg);

#ifndef MSG_SGS_LOCAL_ARRAY
#define	MSG_SGS_LOCAL_ARRAY	""
#endif

extern	const char	__sgs_msg_libconv_relocate_arm[];

#define MSG_ORIG_STRTAB(_x, _s)	_x
#define MSG_ORIG(x)	x
#define MSG_INTL(x)	x

#ifndef LINTSUP_SUPPRESS_STRINGS

#define	MSG_R_ARM_NONE	"R_ARM_NONE"
#define	MSG_R_ARM_NONE_SIZE	10

#define	MSG_R_ARM_PC24	"R_ARM_PC24"
#define	MSG_R_ARM_PC24_SIZE	10

#define	MSG_R_ARM_ABS32	"R_ARM_ABS32"
#define	MSG_R_ARM_ABS32_SIZE	11

#define	MSG_R_ARM_REL32	"R_ARM_REL32"
#define	MSG_R_ARM_REL32_SIZE	11

#define	MSG_R_ARM_LDR_PC_G0	"R_ARM_LDR_PC_G0"
#define	MSG_R_ARM_LDR_PC_G0_SIZE	15

#define	MSG_R_ARM_ABS16	"R_ARM_ABS16"
#define	MSG_R_ARM_ABS16_SIZE	11

#define	MSG_R_ARM_ABS12	"R_ARM_ABS12"
#define	MSG_R_ARM_ABS12_SIZE	11

#define	MSG_R_ARM_THM_ABS5	"R_ARM_THM_ABS5"
#define	MSG_R_ARM_THM_ABS5_SIZE	14

#define	MSG_R_ARM_ABS8	"R_ARM_ABS8"
#define	MSG_R_ARM_ABS8_SIZE	10

#define	MSG_R_ARM_SBREL32	"R_ARM_SBREL32"
#define	MSG_R_ARM_SBREL32_SIZE	13

#define	MSG_R_ARM_THM_CALL	"R_ARM_THM_CALL"
#define	MSG_R_ARM_THM_CALL_SIZE	14

#define	MSG_R_ARM_THM_PC8	"R_ARM_THM_PC8"
#define	MSG_R_ARM_THM_PC8_SIZE	13

#define	MSG_R_ARM_BREL_ADJ	"R_ARM_BREL_ADJ"
#define	MSG_R_ARM_BREL_ADJ_SIZE	14

#define	MSG_R_ARM_TLS_DESC	"R_ARM_TLS_DESC"
#define	MSG_R_ARM_TLS_DESC_SIZE	14

#define	MSG_R_ARM_THM_SWI8	"R_ARM_THM_SWI8"
#define	MSG_R_ARM_THM_SWI8_SIZE	14

#define	MSG_R_ARM_XPC25	"R_ARM_XPC25"
#define	MSG_R_ARM_XPC25_SIZE	11

#define	MSG_R_ARM_THM_XPC22	"R_ARM_THM_XPC22"
#define	MSG_R_ARM_THM_XPC22_SIZE	15

#define	MSG_R_ARM_TLS_DTPMOD32	"R_ARM_TLS_DTPMOD32"
#define	MSG_R_ARM_TLS_DTPMOD32_SIZE	18

#define	MSG_R_ARM_TLS_DTOFF32	"R_ARM_TLS_DTOFF32"
#define	MSG_R_ARM_TLS_DTOFF32_SIZE	17

#define	MSG_R_ARM_TLS_TPOFF32	"R_ARM_TLS_TPOFF32"
#define	MSG_R_ARM_TLS_TPOFF32_SIZE	17

#define	MSG_R_ARM_COPY	"R_ARM_COPY"
#define	MSG_R_ARM_COPY_SIZE	10

#define	MSG_R_ARM_GLOB_DAT	"R_ARM_GLOB_DAT"
#define	MSG_R_ARM_GLOB_DAT_SIZE	14

#define	MSG_R_ARM_JUMP_SLOT	"R_ARM_JUMP_SLOT"
#define	MSG_R_ARM_JUMP_SLOT_SIZE	15

#define	MSG_R_ARM_RELATIVE	"R_ARM_RELATIVE"
#define	MSG_R_ARM_RELATIVE_SIZE	14

#define	MSG_R_ARM_GOTOFF32	"R_ARM_GOTOFF32"
#define	MSG_R_ARM_GOTOFF32_SIZE	14

#define	MSG_R_ARM_BASE_PREL	"R_ARM_BASE_PREL"
#define	MSG_R_ARM_BASE_PREL_SIZE	15

#define	MSG_R_ARM_GOT_BREL	"R_ARM_GOT_BREL"
#define	MSG_R_ARM_GOT_BREL_SIZE	14

#define	MSG_R_ARM_PLT32	"R_ARM_PLT32"
#define	MSG_R_ARM_PLT32_SIZE	11

#define	MSG_R_ARM_CALL	"R_ARM_CALL"
#define	MSG_R_ARM_CALL_SIZE	10

#define	MSG_R_ARM_JUMP24	"R_ARM_JUMP24"
#define	MSG_R_ARM_JUMP24_SIZE	12

#define	MSG_R_ARM_THM_JUMP24	"R_ARM_THM_JUMP24"
#define	MSG_R_ARM_THM_JUMP24_SIZE	16

#define	MSG_R_ARM_BASE_ABS	"R_ARM_BASE_ABS"
#define	MSG_R_ARM_BASE_ABS_SIZE	14

#define	MSG_R_ARM_ALU_PCREL_7_0	"R_ARM_ALU_PCREL_7_0"
#define	MSG_R_ARM_ALU_PCREL_7_0_SIZE	19

#define	MSG_R_ARM_ALU_PCREL_15_8	"R_ARM_ALU_PCREL_15_8"
#define	MSG_R_ARM_ALU_PCREL_15_8_SIZE	20

#define	MSG_R_ARM_ALU_PCREL_23_15	"R_ARM_ALU_PCREL_23_15"
#define	MSG_R_ARM_ALU_PCREL_23_15_SIZE	21

#define	MSG_R_ARM_LDR_SBREL_11_0_NC	"R_ARM_LDR_SBREL_11_0_NC"
#define	MSG_R_ARM_LDR_SBREL_11_0_NC_SIZE	23

#define	MSG_R_ARM_ALU_SBREL_19_12_NC	"R_ARM_ALU_SBREL_19_12_NC"
#define	MSG_R_ARM_ALU_SBREL_19_12_NC_SIZE	24

#define	MSG_R_ARM_ALU_SBREL_27_20_CK	"R_ARM_ALU_SBREL_27_20_CK"
#define	MSG_R_ARM_ALU_SBREL_27_20_CK_SIZE	24

#define	MSG_R_ARM_TARGET1	"R_ARM_TARGET1"
#define	MSG_R_ARM_TARGET1_SIZE	13

#define	MSG_R_ARM_SBREL31	"R_ARM_SBREL31"
#define	MSG_R_ARM_SBREL31_SIZE	13

#define	MSG_R_ARM_V4BX	"R_ARM_V4BX"
#define	MSG_R_ARM_V4BX_SIZE	10

#define	MSG_R_ARM_TARGET2	"R_ARM_TARGET2"
#define	MSG_R_ARM_TARGET2_SIZE	13

#define	MSG_R_ARM_PREL31	"R_ARM_PREL31"
#define	MSG_R_ARM_PREL31_SIZE	12

#define	MSG_R_ARM_MOVW_ABS_NC	"R_ARM_MOVW_ABS_NC"
#define	MSG_R_ARM_MOVW_ABS_NC_SIZE	17

#define	MSG_R_ARM_MOVT_ABS	"R_ARM_MOVT_ABS"
#define	MSG_R_ARM_MOVT_ABS_SIZE	14

#define	MSG_R_ARM_MOVW_PREL_NC	"R_ARM_MOVW_PREL_NC"
#define	MSG_R_ARM_MOVW_PREL_NC_SIZE	18

#define	MSG_R_ARM_MOVT_PREL	"R_ARM_MOVT_PREL"
#define	MSG_R_ARM_MOVT_PREL_SIZE	15

#define	MSG_R_ARM_THM_MOVW_ABS_NC	"R_ARM_THM_MOVW_ABS_NC"
#define	MSG_R_ARM_THM_MOVW_ABS_NC_SIZE	21

#define	MSG_R_ARM_THM_MOVT_ABS	"R_ARM_THM_MOVT_ABS"
#define	MSG_R_ARM_THM_MOVT_ABS_SIZE	18

#define	MSG_R_ARM_THM_MOVW_PREL_NC	"R_ARM_THM_MOVW_PREL_NC"
#define	MSG_R_ARM_THM_MOVW_PREL_NC_SIZE	22

#define	MSG_R_ARM_THM_MOVT_PREL	"R_ARM_THM_MOVT_PREL"
#define	MSG_R_ARM_THM_MOVT_PREL_SIZE	19

#define	MSG_R_ARM_THM_JUMP19	"R_ARM_THM_JUMP19"
#define	MSG_R_ARM_THM_JUMP19_SIZE	16

#define	MSG_R_ARM_THM_JUMP6	"R_ARM_THM_JUMP6"
#define	MSG_R_ARM_THM_JUMP6_SIZE	15

#define	MSG_R_ARM_THM_ALU_PREL_11_0	"R_ARM_THM_ALU_PREL_11_0"
#define	MSG_R_ARM_THM_ALU_PREL_11_0_SIZE	23

#define	MSG_R_ARM_THM_PC12	"R_ARM_THM_PC12"
#define	MSG_R_ARM_THM_PC12_SIZE	14

#define	MSG_R_ARM_ABS32_NOI	"R_ARM_ABS32_NOI"
#define	MSG_R_ARM_ABS32_NOI_SIZE	15

#define	MSG_R_ARM_REL32_NOI	"R_ARM_REL32_NOI"
#define	MSG_R_ARM_REL32_NOI_SIZE	15

#define	MSG_R_ARM_ALU_PC_G0_NC	"R_ARM_ALU_PC_G0_NC"
#define	MSG_R_ARM_ALU_PC_G0_NC_SIZE	18

#define	MSG_R_ARM_ALU_PC_G0	"R_ARM_ALU_PC_G0"
#define	MSG_R_ARM_ALU_PC_G0_SIZE	15

#define	MSG_R_ARM_ALU_PC_G1_NC	"R_ARM_ALU_PC_G1_NC"
#define	MSG_R_ARM_ALU_PC_G1_NC_SIZE	18

#define	MSG_R_ARM_ALU_PC_G1	"R_ARM_ALU_PC_G1"
#define	MSG_R_ARM_ALU_PC_G1_SIZE	15

#define	MSG_R_ARM_ALU_PC_G2	"R_ARM_ALU_PC_G2"
#define	MSG_R_ARM_ALU_PC_G2_SIZE	15

#define	MSG_R_ARM_LDR_PC_G1	"R_ARM_LDR_PC_G1"
#define	MSG_R_ARM_LDR_PC_G1_SIZE	15

#define	MSG_R_ARM_LDR_PC_G2	"R_ARM_LDR_PC_G2"
#define	MSG_R_ARM_LDR_PC_G2_SIZE	15

#define	MSG_R_ARM_LDRS_PC_G0	"R_ARM_LDRS_PC_G0"
#define	MSG_R_ARM_LDRS_PC_G0_SIZE	16

#define	MSG_R_ARM_LDRS_PC_G1	"R_ARM_LDRS_PC_G1"
#define	MSG_R_ARM_LDRS_PC_G1_SIZE	16

#define	MSG_R_ARM_LDRS_PC_G2	"R_ARM_LDRS_PC_G2"
#define	MSG_R_ARM_LDRS_PC_G2_SIZE	16

#define	MSG_R_ARM_LDC_PC_G0	"R_ARM_LDC_PC_G0"
#define	MSG_R_ARM_LDC_PC_G0_SIZE	15

#define	MSG_R_ARM_LDC_PC_G1	"R_ARM_LDC_PC_G1"
#define	MSG_R_ARM_LDC_PC_G1_SIZE	15

#define	MSG_R_ARM_LDC_PC_G2	"R_ARM_LDC_PC_G2"
#define	MSG_R_ARM_LDC_PC_G2_SIZE	15

#define	MSG_R_ARM_ALU_SB_G0_NC	"R_ARM_ALU_SB_G0_NC"
#define	MSG_R_ARM_ALU_SB_G0_NC_SIZE	18

#define	MSG_R_ARM_ALU_SB_G0	"R_ARM_ALU_SB_G0"
#define	MSG_R_ARM_ALU_SB_G0_SIZE	15

#define	MSG_R_ARM_ALU_SB_G1_NC	"R_ARM_ALU_SB_G1_NC"
#define	MSG_R_ARM_ALU_SB_G1_NC_SIZE	18

#define	MSG_R_ARM_ALU_SB_G1	"R_ARM_ALU_SB_G1"
#define	MSG_R_ARM_ALU_SB_G1_SIZE	15

#define	MSG_R_ARM_ALU_SB_G2	"R_ARM_ALU_SB_G2"
#define	MSG_R_ARM_ALU_SB_G2_SIZE	15

#define	MSG_R_ARM_LDR_SB_G0	"R_ARM_LDR_SB_G0"
#define	MSG_R_ARM_LDR_SB_G0_SIZE	15

#define	MSG_R_ARM_LDR_SB_G1	"R_ARM_LDR_SB_G1"
#define	MSG_R_ARM_LDR_SB_G1_SIZE	15

#define	MSG_R_ARM_LDR_SB_G2	"R_ARM_LDR_SB_G2"
#define	MSG_R_ARM_LDR_SB_G2_SIZE	15

#define	MSG_R_ARM_LDRS_SB_G0	"R_ARM_LDRS_SB_G0"
#define	MSG_R_ARM_LDRS_SB_G0_SIZE	16

#define	MSG_R_ARM_LDRS_SB_G1	"R_ARM_LDRS_SB_G1"
#define	MSG_R_ARM_LDRS_SB_G1_SIZE	16

#define	MSG_R_ARM_LDRS_SB_G2	"R_ARM_LDRS_SB_G2"
#define	MSG_R_ARM_LDRS_SB_G2_SIZE	16

#define	MSG_R_ARM_LDC_SB_G0	"R_ARM_LDC_SB_G0"
#define	MSG_R_ARM_LDC_SB_G0_SIZE	15

#define	MSG_R_ARM_LDC_SB_G1	"R_ARM_LDC_SB_G1"
#define	MSG_R_ARM_LDC_SB_G1_SIZE	15

#define	MSG_R_ARM_LDC_SB_G2	"R_ARM_LDC_SB_G2"
#define	MSG_R_ARM_LDC_SB_G2_SIZE	15

#define	MSG_R_ARM_MOVW_BREL_NC	"R_ARM_MOVW_BREL_NC"
#define	MSG_R_ARM_MOVW_BREL_NC_SIZE	18

#define	MSG_R_ARM_MOVT_BREL	"R_ARM_MOVT_BREL"
#define	MSG_R_ARM_MOVT_BREL_SIZE	15

#define	MSG_R_ARM_MOVW_BREL	"R_ARM_MOVW_BREL"
#define	MSG_R_ARM_MOVW_BREL_SIZE	15

#define	MSG_R_ARM_THM_MOVW_BREL_NC	"R_ARM_THM_MOVW_BREL_NC"
#define	MSG_R_ARM_THM_MOVW_BREL_NC_SIZE	22

#define	MSG_R_ARM_THM_MOVT_BREL	"R_ARM_THM_MOVT_BREL"
#define	MSG_R_ARM_THM_MOVT_BREL_SIZE	19

#define	MSG_R_ARM_THM_MOVW_BREL	"R_ARM_THM_MOVW_BREL"
#define	MSG_R_ARM_THM_MOVW_BREL_SIZE	19

#define	MSG_R_ARM_TLS_GOTDESC	"R_ARM_TLS_GOTDESC"
#define	MSG_R_ARM_TLS_GOTDESC_SIZE	17

#define	MSG_R_ARM_TLS_CALL	"R_ARM_TLS_CALL"
#define	MSG_R_ARM_TLS_CALL_SIZE	14

#define	MSG_R_ARM_TLS_DESCSEQ	"R_ARM_TLS_DESCSEQ"
#define	MSG_R_ARM_TLS_DESCSEQ_SIZE	17

#define	MSG_R_ARM_THM_TLS_CALL	"R_ARM_THM_TLS_CALL"
#define	MSG_R_ARM_THM_TLS_CALL_SIZE	18

#define	MSG_R_ARM_PLT32_ABS	"R_ARM_PLT32_ABS"
#define	MSG_R_ARM_PLT32_ABS_SIZE	15

#define	MSG_R_ARM_GOT_ABS	"R_ARM_GOT_ABS"
#define	MSG_R_ARM_GOT_ABS_SIZE	13

#define	MSG_R_ARM_GOT_PREL	"R_ARM_GOT_PREL"
#define	MSG_R_ARM_GOT_PREL_SIZE	14

#define	MSG_R_ARM_GOT_BREL12	"R_ARM_GOT_BREL12"
#define	MSG_R_ARM_GOT_BREL12_SIZE	16

#define	MSG_R_ARM_GOTOFF12	"R_ARM_GOTOFF12"
#define	MSG_R_ARM_GOTOFF12_SIZE	14

#define	MSG_R_ARM_GOTRELAX	"R_ARM_GOTRELAX"
#define	MSG_R_ARM_GOTRELAX_SIZE	14

#define	MSG_R_ARM_GNU_VTENTRY	"R_ARM_GNU_VTENTRY"
#define	MSG_R_ARM_GNU_VTENTRY_SIZE	17

#define	MSG_R_ARM_GNU_VTINHERIT	"R_ARM_GNU_VTINHERIT"
#define	MSG_R_ARM_GNU_VTINHERIT_SIZE	19

#define	MSG_R_ARM_THM_JUMP11	"R_ARM_THM_JUMP11"
#define	MSG_R_ARM_THM_JUMP11_SIZE	16

#define	MSG_R_ARM_THM_JUMP8	"R_ARM_THM_JUMP8"
#define	MSG_R_ARM_THM_JUMP8_SIZE	15

#define	MSG_R_ARM_TLS_GD32	"R_ARM_TLS_GD32"
#define	MSG_R_ARM_TLS_GD32_SIZE	14

#define	MSG_R_ARM_TLS_LDM32	"R_ARM_TLS_LDM32"
#define	MSG_R_ARM_TLS_LDM32_SIZE	15

#define	MSG_R_ARM_TLS_LDO32	"R_ARM_TLS_LDO32"
#define	MSG_R_ARM_TLS_LDO32_SIZE	15

#define	MSG_R_ARM_TLS_IE32	"R_ARM_TLS_IE32"
#define	MSG_R_ARM_TLS_IE32_SIZE	14

#define	MSG_R_ARM_TLS_LE32	"R_ARM_TLS_LE32"
#define	MSG_R_ARM_TLS_LE32_SIZE	14

#define	MSG_R_ARM_TLS_LDO12	"R_ARM_TLS_LDO12"
#define	MSG_R_ARM_TLS_LDO12_SIZE	15

#define	MSG_R_ARM_TLS_LE12	"R_ARM_TLS_LE12"
#define	MSG_R_ARM_TLS_LE12_SIZE	14

#define	MSG_R_ARM_TLS_IE12GP	"R_ARM_TLS_IE12GP"
#define	MSG_R_ARM_TLS_IE12GP_SIZE	16

#define	MSG_R_ARM_PRIVATE_0	"R_ARM_PRIVATE_0"
#define	MSG_R_ARM_PRIVATE_0_SIZE	15

#define	MSG_R_ARM_PRIVATE_1	"R_ARM_PRIVATE_1"
#define	MSG_R_ARM_PRIVATE_1_SIZE	15

#define	MSG_R_ARM_PRIVATE_2	"R_ARM_PRIVATE_2"
#define	MSG_R_ARM_PRIVATE_2_SIZE	15

#define	MSG_R_ARM_PRIVATE_3	"R_ARM_PRIVATE_3"
#define	MSG_R_ARM_PRIVATE_3_SIZE	15

#define	MSG_R_ARM_PRIVATE_4	"R_ARM_PRIVATE_4"
#define	MSG_R_ARM_PRIVATE_4_SIZE	15

#define	MSG_R_ARM_PRIVATE_5	"R_ARM_PRIVATE_5"
#define	MSG_R_ARM_PRIVATE_5_SIZE	15

#define	MSG_R_ARM_PRIVATE_6	"R_ARM_PRIVATE_6"
#define	MSG_R_ARM_PRIVATE_6_SIZE	15

#define	MSG_R_ARM_PRIVATE_7	"R_ARM_PRIVATE_7"
#define	MSG_R_ARM_PRIVATE_7_SIZE	15

#define	MSG_R_ARM_PRIVATE_8	"R_ARM_PRIVATE_8"
#define	MSG_R_ARM_PRIVATE_8_SIZE	15

#define	MSG_R_ARM_PRIVATE_9	"R_ARM_PRIVATE_9"
#define	MSG_R_ARM_PRIVATE_9_SIZE	15

#define	MSG_R_ARM_PRIVATE_10	"R_ARM_PRIVATE_10"
#define	MSG_R_ARM_PRIVATE_10_SIZE	16

#define	MSG_R_ARM_PRIVATE_11	"R_ARM_PRIVATE_11"
#define	MSG_R_ARM_PRIVATE_11_SIZE	16

#define	MSG_R_ARM_PRIVATE_12	"R_ARM_PRIVATE_12"
#define	MSG_R_ARM_PRIVATE_12_SIZE	16

#define	MSG_R_ARM_PRIVATE_13	"R_ARM_PRIVATE_13"
#define	MSG_R_ARM_PRIVATE_13_SIZE	16

#define	MSG_R_ARM_PRIVATE_14	"R_ARM_PRIVATE_14"
#define	MSG_R_ARM_PRIVATE_14_SIZE	16

#define	MSG_R_ARM_PRIVATE_15	"R_ARM_PRIVATE_15"
#define	MSG_R_ARM_PRIVATE_15_SIZE	16

#define	MSG_R_ARM_ME_TOO	"R_ARM_ME_TOO"
#define	MSG_R_ARM_ME_TOO_SIZE	12

#define	MSG_R_ARM_THM_TLS_DESCSEQ16	"R_ARM_THM_TLS_DESCSEQ16"
#define	MSG_R_ARM_THM_TLS_DESCSEQ16_SIZE	23

#define	MSG_R_ARM_THM_TLS_DESCSEQ32	"R_ARM_THM_TLS_DESCSEQ32"
#define	MSG_R_ARM_THM_TLS_DESCSEQ32_SIZE	23

#define	MSG_R_ARM_THM_GOT_BREL12	"R_ARM_THM_GOT_BREL12"
#define	MSG_R_ARM_THM_GOT_BREL12_SIZE	20

#define	MSG_R_ARM_IRELATIVE	"R_ARM_IRELATIVE"
#define	MSG_R_ARM_IRELATIVE_SIZE	15

#endif	/* LINTSUP_SUPPRESS_STRINGS */

#endif	/* __lint */

#endif
