/*
 * This file and its contents are supplied under the terms of the
 * Common Development and Distribution License ("CDDL"), version 1.0.
 * You may only use this file in accordance with the terms of version
 * 1.0 of the CDDL.
 *
 * A full copy of the text of the CDDL should have accompanied this
 * source.  A copy of the CDDL is also available via the Internet at
 * http://www.illumos.org/license/CDDL.
 */

#include <sys/elf_ARM.h>
#include "_conv.h"
#include <armattrs_msg.h>

const char *
conv_arm_tag(uint_t tag, Conv_fmt_flags_t fmt_flags, Conv_inv_buf_t *inv_buf)
{
	static const Val_desc tags[] = {
		{ ARM_TAG_FILE, MSG_ARM_TAG_FILE },
		{ ARM_TAG_SECTION, MSG_ARM_TAG_SECTION },
		{ ARM_TAG_SYMBOL, MSG_ARM_TAG_SYMBOL },
		{ ARM_TAG_CPU_RAW_NAME, MSG_ARM_TAG_CPU_RAW_NAME },
		{ ARM_TAG_CPU_NAME, MSG_ARM_TAG_CPU_NAME },
		{ ARM_TAG_CPU_ARCH, MSG_ARM_TAG_CPU_ARCH },
		{ ARM_TAG_CPU_ARCH_PROFILE, MSG_ARM_TAG_CPU_ARCH_PROFILE },
		{ ARM_TAG_ARM_ISA_USE, MSG_ARM_TAG_ARM_ISA_USE },
		{ ARM_TAG_THUMB_ISA_USE, MSG_ARM_TAG_THUMB_ISA_USE },
		{ ARM_TAG_FP_ARCH, MSG_ARM_TAG_FP_ARCH },
		{ ARM_TAG_WWMX_ARCH, MSG_ARM_TAG_WWMX_ARCH },
		{ ARM_TAG_ADVANCED_SIMD_ARCH, MSG_ARM_TAG_ADVANCED_SIMD_ARCH },
		{ ARM_TAG_ABI_PCS_CONFIG, MSG_ARM_TAG_ABI_PCS_CONFIG },
		{ ARM_TAG_ABI_PCS_R9_USE, MSG_ARM_TAG_ABI_PCS_R9_USE },
		{ ARM_TAG_ABI_PCS_RW_DATA, MSG_ARM_TAG_ABI_PCS_RW_DATA },
		{ ARM_TAG_ABI_PCS_RO_DATA, MSG_ARM_TAG_ABI_PCS_RO_DATA },
		{ ARM_TAG_ABI_PCS_GOT_USE, MSG_ARM_TAG_ABI_PCS_GOT_USE },
		{ ARM_TAG_ABI_PCS_WCHAR_T, MSG_ARM_TAG_ABI_PCS_WCHAR_T },
		{ ARM_TAG_ABI_FP_ROUNDING, MSG_ARM_TAG_ABI_FP_ROUNDING },
		{ ARM_TAG_ABI_FP_DENORMAL, MSG_ARM_TAG_ABI_FP_DENORMAL },
		{ ARM_TAG_ABI_FP_EXCEPTIONS, MSG_ARM_TAG_ABI_FP_EXCEPTIONS },
		{ ARM_TAG_ABI_FP_USER_EXCEPTIONS, MSG_ARM_TAG_ABI_FP_USER_EXCEPTIONS },
		{ ARM_TAG_ABI_FP_NUMBER_MODEL, MSG_ARM_TAG_ABI_FP_NUMBER_MODEL },
		{ ARM_TAG_ABI_ALIGN_NEEDED, MSG_ARM_TAG_ABI_ALIGN_NEEDED },
		{ ARM_TAG_ABI_ALIGN_PRESERVED, MSG_ARM_TAG_ABI_ALIGN_PRESERVED },
		{ ARM_TAG_ABI_ENUM_SIZE, MSG_ARM_TAG_ABI_ENUM_SIZE },
		{ ARM_TAG_ABI_HARDFP_USE, MSG_ARM_TAG_ABI_HARDFP_USE },
		{ ARM_TAG_ABI_VFP_ARGS, MSG_ARM_TAG_ABI_VFP_ARGS },
		{ ARM_TAG_ABI_WMMX_ARGS, MSG_ARM_TAG_ABI_WMMX_ARGS },
		{ ARM_TAG_ABI_OPTIMIZATION_GOALS, MSG_ARM_TAG_ABI_OPTIMIZATION_GOALS },
		{ ARM_TAG_ABI_FP_OPTIMIZATION_GOALS, MSG_ARM_TAG_ABI_FP_OPTIMIZATION_GOALS },
		{ ARM_TAG_COMPATIBILITY, MSG_ARM_TAG_COMPATIBILITY },
		{ ARM_TAG_UNALIGNED_ACCESS, MSG_ARM_TAG_UNALIGNED_ACCESS },
		{ ARM_TAG_FP_HP_EXTENSION, MSG_ARM_TAG_FP_HP_EXTENSION },
		{ ARM_TAG_ABI_16BIT_FORMAT, MSG_ARM_TAG_ABI_16BIT_FORMAT },
		{ ARM_TAG_MPEXTENSION_USE, MSG_ARM_TAG_MPEXTENSION_USE },
		{ ARM_TAG_DIV_USE, MSG_ARM_TAG_DIV_USE },
		{ ARM_TAG_NODEFAULTS, MSG_ARM_TAG_NODEFAULTS },
		{ ARM_TAG_ALSO_COMPATIBLE_WITH, MSG_ARM_TAG_ALSO_COMPATIBLE_WITH },
		{ ARM_TAG_T2EE_USE, MSG_ARM_TAG_T2EE_USE },
		{ ARM_TAG_CONFORMANCE, MSG_ARM_TAG_CONFORMANCE },
		{ ARM_TAG_VIRTUALIZATION_USE, MSG_ARM_TAG_VIRTUALIZATION_USE },
		{ ARM_TAG_MPEXTENSION_USE_2, MSG_ARM_TAG_MPEXTENSION_USE_2 },
		{ 0 }
	};

	static const conv_ds_vd_t ds_vd_tag = {
		CONV_DS_VD, ARM_TAG_FILE, ARM_TAG_MPEXTENSION_USE_2, tags
	};
	static const conv_ds_t *ds_tag[] = { CONV_DS_ADDR(ds_vd_tag), NULL };

	return (conv_map_ds(ELFOSABI_NONE, EM_NONE, tag, ds_tag, fmt_flags,
	    inv_buf));
}
