#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2013, Joyent, Inc.  All rights reserved.
#


#
# Kernel runtime-linker
#
KRTLD_INC_PATH	= -I$(UTSBASE)/common/krtld -I$(UTSBASE)/arm/sys
KRTLD_INC_PATH	+= -I$(UTSBASE)/arm/krtld

KRTLD_CPPFLAGS_32	= -DELF_TARGET_ARM
KRTLD_CPPFLAGS		= $(KRTLD_CPPFLAGS_$(CLASS)) -D_KRTLD

$(OBJS_DIR)/%.o:	$(UTSBASE)/common/krtld/%.c
	$(COMPILE.c) $(KRTLD_INC_PATH) $(KRTLD_CPPFLAGS) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:	$(UTSBASE)/arm/krtld/%.c
	$(COMPILE.c) $(KRTLD_INC_PATH) $(KRTLD_CPPFLAGS) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:	$(UTSBASE)/arm/krtld/%.s
	$(COMPILE.s) $(KRTLD_INC_PATH) $(KRTLD_CPPFLAGS) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:	$(UTSBASE)/arm/ml/%.s
	$(COMPILE.s) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSBASE)/arm/promif/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)


$(OBJS_DIR)/%.o:		$(SRC)/common/fs/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSBASE)/arm/misc/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

# XXX Do we keep this CPPFLAG?
$(OBJS_DIR)/kobj.o		:= CPPFLAGS += -D_DBOOT


