#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
# Copyright 2018, Joyent, Inc.
#
# Makefile for interrupt distribution daemon
#

PROG=		intrd
OBJS=		intrd.o intrd_kstat.o intrd_move.o
SRCS=		$(OBJS:%.o=%.c)

MANIFEST=	intrd.xml
SVCMETHOD=	svc-intrd

include ../Makefile.cmd
include ../Makefile.cmd.64
include ../Makefile.ctf

CSTD=	$(CSTD_GNU99)
LDLIBS +=	-lkstat -lcustr -lcmdutils -llgrp -lumem

TARGET=	all

ROOTMANIFESTDIR=	$(ROOTSVCSYSTEM)

# install macros and rule
#
ROOTPROG=	$(ROOTLIB)/$(PROG)
$(ROOTPROG)	:= FILEMODE= 555

.KEEP_STATE:

all: $(PROG)

$(PROG): $(OBJS)
	$(LINK.c) -o $@ $(OBJS) $(LDLIBS)
	$(POST_PROCESS)

install: all .WAIT $(ROOTPROG) $(ROOTMANIFEST) $(ROOTSVCMETHOD)

clean:
	rm $(OBJS)

check:	$(CHKMANIFEST)

${ROOTLIB}/%: %
	${INS.file}

lint:

include ../Makefile.targ
