/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <sys/param.h>
#include <sys/systm.h>
#include <rpcsvc/nsm_addr.h>
/*
 * Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 *
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License, Version 1.0 only
 * (the "License").  You may not use this file except in compliance
 * with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

#pragma ident	"%Z%%M%	%I%	%E% SMI"

/* from nsm_addr.x */

/*
 * This is the definition for the REG procedure which is used
 * to register name/address pairs with statd.
 */


/*
 * This is the definition for the UNREG procedure which is used
 * to unregister an address (and its associated name, if that name
 * has no other addresses registered with it) with statd.
 */

/*
 * This is the definition for the NSM address registration network
 * protocol which is used to privately support address registration
 * with the status daemon statd (NSM).
 */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
nsmaddrproc1_null_1(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NSMADDRPROC1_NULL,
		(xdrproc_t)xdr_void, (caddr_t)argp,
		(xdrproc_t)xdr_void, (caddr_t)clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nsmaddrproc1_reg_1(reg1args *argp, reg1res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NSMADDRPROC1_REG,
		(xdrproc_t)xdr_reg1args, (caddr_t)argp,
		(xdrproc_t)xdr_reg1res, (caddr_t)clnt_res,
		TIMEOUT));
}

enum clnt_stat 
nsmaddrproc1_unreg_1(unreg1args *argp, unreg1res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NSMADDRPROC1_UNREG,
		(xdrproc_t)xdr_unreg1args, (caddr_t)argp,
		(xdrproc_t)xdr_unreg1res, (caddr_t)clnt_res,
		TIMEOUT));
}
