/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <sys/param.h>
#include <sys/systm.h>
#include <rpcsvc/sm_inter.h>
/*
 * Copyright (c) 1986, 1994 by Sun Microsystems, Inc.
 * All rights reserved.
 */
/* from sm_inter.x */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
sm_stat_1(struct sm_name *argp, struct sm_stat_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SM_STAT,
		(xdrproc_t)xdr_sm_name, (caddr_t)argp,
		(xdrproc_t)xdr_sm_stat_res, (caddr_t)clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sm_mon_1(struct mon *argp, struct sm_stat_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SM_MON,
		(xdrproc_t)xdr_mon, (caddr_t)argp,
		(xdrproc_t)xdr_sm_stat_res, (caddr_t)clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sm_unmon_1(struct mon_id *argp, struct sm_stat *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SM_UNMON,
		(xdrproc_t)xdr_mon_id, (caddr_t)argp,
		(xdrproc_t)xdr_sm_stat, (caddr_t)clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sm_unmon_all_1(struct my_id *argp, struct sm_stat *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SM_UNMON_ALL,
		(xdrproc_t)xdr_my_id, (caddr_t)argp,
		(xdrproc_t)xdr_sm_stat, (caddr_t)clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sm_simu_crash_1(void *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SM_SIMU_CRASH,
		(xdrproc_t)xdr_void, (caddr_t)argp,
		(xdrproc_t)xdr_void, (caddr_t)clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sm_notify_1(struct stat_chge *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SM_NOTIFY,
		(xdrproc_t)xdr_stat_chge, (caddr_t)argp,
		(xdrproc_t)xdr_void, (caddr_t)clnt_res,
		TIMEOUT));
}
