#ifndef	_ARMATTRS_MSG_DOT_H
#define	_ARMATTRS_MSG_DOT_H

#include <sgsmsg.h>	/* Msg typedef */

#ifndef	__lint

#define	MSG_SGS_LOCAL_ARRAY	__sgs_msg_libconv_armattrs

extern	const char	__sgs_msg_libconv_armattrs[];

#define	MSG_ORIG_STRTAB(_x, _s)	&_s[_x]

#define	MSG_ORIG(x)	MSG_ORIG_STRTAB(x, __sgs_msg_libconv_armattrs)

extern	const char *	_sgs_msg_libconv_armattrs(Msg);

#define	MSG_INTL(x)	_sgs_msg_libconv_armattrs(x)


#define	MSG_ARM_TAG_FILE	1
#define	MSG_ARM_TAG_FILE_SIZE	12

#define	MSG_ARM_TAG_SECTION	14
#define	MSG_ARM_TAG_SECTION_SIZE	15

#define	MSG_ARM_TAG_SYMBOL	30
#define	MSG_ARM_TAG_SYMBOL_SIZE	14

#define	MSG_ARM_TAG_CPU_RAW_NAME	45
#define	MSG_ARM_TAG_CPU_RAW_NAME_SIZE	20

#define	MSG_ARM_TAG_CPU_NAME	66
#define	MSG_ARM_TAG_CPU_NAME_SIZE	16

#define	MSG_ARM_TAG_CPU_ARCH	83
#define	MSG_ARM_TAG_CPU_ARCH_SIZE	16

#define	MSG_ARM_TAG_CPU_ARCH_PROFILE	100
#define	MSG_ARM_TAG_CPU_ARCH_PROFILE_SIZE	24

#define	MSG_ARM_TAG_ARM_ISA_USE	125
#define	MSG_ARM_TAG_ARM_ISA_USE_SIZE	19

#define	MSG_ARM_TAG_THUMB_ISA_USE	145
#define	MSG_ARM_TAG_THUMB_ISA_USE_SIZE	21

#define	MSG_ARM_TAG_FP_ARCH	167
#define	MSG_ARM_TAG_FP_ARCH_SIZE	15

#define	MSG_ARM_TAG_WWMX_ARCH	183
#define	MSG_ARM_TAG_WWMX_ARCH_SIZE	17

#define	MSG_ARM_TAG_ADVANCED_SIMD_ARCH	201
#define	MSG_ARM_TAG_ADVANCED_SIMD_ARCH_SIZE	26

#define	MSG_ARM_TAG_ABI_PCS_CONFIG	228
#define	MSG_ARM_TAG_ABI_PCS_CONFIG_SIZE	22

#define	MSG_ARM_TAG_ABI_PCS_R9_USE	251
#define	MSG_ARM_TAG_ABI_PCS_R9_USE_SIZE	22

#define	MSG_ARM_TAG_ABI_PCS_RW_DATA	274
#define	MSG_ARM_TAG_ABI_PCS_RW_DATA_SIZE	23

#define	MSG_ARM_TAG_ABI_PCS_RO_DATA	298
#define	MSG_ARM_TAG_ABI_PCS_RO_DATA_SIZE	23

#define	MSG_ARM_TAG_ABI_PCS_GOT_USE	322
#define	MSG_ARM_TAG_ABI_PCS_GOT_USE_SIZE	23

#define	MSG_ARM_TAG_ABI_PCS_WCHAR_T	346
#define	MSG_ARM_TAG_ABI_PCS_WCHAR_T_SIZE	23

#define	MSG_ARM_TAG_ABI_FP_ROUNDING	370
#define	MSG_ARM_TAG_ABI_FP_ROUNDING_SIZE	23

#define	MSG_ARM_TAG_ABI_FP_DENORMAL	394
#define	MSG_ARM_TAG_ABI_FP_DENORMAL_SIZE	23

#define	MSG_ARM_TAG_ABI_FP_EXCEPTIONS	418
#define	MSG_ARM_TAG_ABI_FP_EXCEPTIONS_SIZE	25

#define	MSG_ARM_TAG_ABI_FP_USER_EXCEPTIONS	444
#define	MSG_ARM_TAG_ABI_FP_USER_EXCEPTIONS_SIZE	30

#define	MSG_ARM_TAG_ABI_FP_NUMBER_MODEL	475
#define	MSG_ARM_TAG_ABI_FP_NUMBER_MODEL_SIZE	27

#define	MSG_ARM_TAG_ABI_ALIGN_NEEDED	503
#define	MSG_ARM_TAG_ABI_ALIGN_NEEDED_SIZE	24

#define	MSG_ARM_TAG_ABI_ALIGN_PRESERVED	528
#define	MSG_ARM_TAG_ABI_ALIGN_PRESERVED_SIZE	27

#define	MSG_ARM_TAG_ABI_ENUM_SIZE	556
#define	MSG_ARM_TAG_ABI_ENUM_SIZE_SIZE	21

#define	MSG_ARM_TAG_ABI_HARDFP_USE	578
#define	MSG_ARM_TAG_ABI_HARDFP_USE_SIZE	22

#define	MSG_ARM_TAG_ABI_VFP_ARGS	601
#define	MSG_ARM_TAG_ABI_VFP_ARGS_SIZE	20

#define	MSG_ARM_TAG_ABI_WMMX_ARGS	622
#define	MSG_ARM_TAG_ABI_WMMX_ARGS_SIZE	21

#define	MSG_ARM_TAG_ABI_OPTIMIZATION_GOALS	644
#define	MSG_ARM_TAG_ABI_OPTIMIZATION_GOALS_SIZE	30

#define	MSG_ARM_TAG_ABI_FP_OPTIMIZATION_GOALS	675
#define	MSG_ARM_TAG_ABI_FP_OPTIMIZATION_GOALS_SIZE	33

#define	MSG_ARM_TAG_COMPATIBILITY	709
#define	MSG_ARM_TAG_COMPATIBILITY_SIZE	21

#define	MSG_ARM_TAG_UNALIGNED_ACCESS	731
#define	MSG_ARM_TAG_UNALIGNED_ACCESS_SIZE	24

#define	MSG_ARM_TAG_FP_HP_EXTENSION	756
#define	MSG_ARM_TAG_FP_HP_EXTENSION_SIZE	23

#define	MSG_ARM_TAG_ABI_16BIT_FORMAT	780
#define	MSG_ARM_TAG_ABI_16BIT_FORMAT_SIZE	24

#define	MSG_ARM_TAG_MPEXTENSION_USE	805
#define	MSG_ARM_TAG_MPEXTENSION_USE_SIZE	23

#define	MSG_ARM_TAG_DIV_USE	829
#define	MSG_ARM_TAG_DIV_USE_SIZE	15

#define	MSG_ARM_TAG_NODEFAULTS	845
#define	MSG_ARM_TAG_NODEFAULTS_SIZE	18

#define	MSG_ARM_TAG_ALSO_COMPATIBLE_WITH	864
#define	MSG_ARM_TAG_ALSO_COMPATIBLE_WITH_SIZE	28

#define	MSG_ARM_TAG_T2EE_USE	893
#define	MSG_ARM_TAG_T2EE_USE_SIZE	16

#define	MSG_ARM_TAG_CONFORMANCE	910
#define	MSG_ARM_TAG_CONFORMANCE_SIZE	19

#define	MSG_ARM_TAG_VIRTUALIZATION_USE	930
#define	MSG_ARM_TAG_VIRTUALIZATION_USE_SIZE	26

#define	MSG_ARM_TAG_MPEXTENSION_USE_2	957
#define	MSG_ARM_TAG_MPEXTENSION_USE_2_SIZE	25

#else	/* __lint */

extern	const char *	_sgs_msg_libconv_armattrs(Msg);

#ifndef MSG_SGS_LOCAL_ARRAY
#define	MSG_SGS_LOCAL_ARRAY	""
#endif

extern	const char	__sgs_msg_libconv_armattrs[];

#define MSG_ORIG_STRTAB(_x, _s)	_x
#define MSG_ORIG(x)	x
#define MSG_INTL(x)	x

#ifndef LINTSUP_SUPPRESS_STRINGS

#define	MSG_ARM_TAG_FILE	"ARM_TAG_FILE"
#define	MSG_ARM_TAG_FILE_SIZE	12

#define	MSG_ARM_TAG_SECTION	"ARM_TAG_SECTION"
#define	MSG_ARM_TAG_SECTION_SIZE	15

#define	MSG_ARM_TAG_SYMBOL	"ARM_TAG_SYMBOL"
#define	MSG_ARM_TAG_SYMBOL_SIZE	14

#define	MSG_ARM_TAG_CPU_RAW_NAME	"ARM_TAG_CPU_RAW_NAME"
#define	MSG_ARM_TAG_CPU_RAW_NAME_SIZE	20

#define	MSG_ARM_TAG_CPU_NAME	"ARM_TAG_CPU_NAME"
#define	MSG_ARM_TAG_CPU_NAME_SIZE	16

#define	MSG_ARM_TAG_CPU_ARCH	"ARM_TAG_CPU_ARCH"
#define	MSG_ARM_TAG_CPU_ARCH_SIZE	16

#define	MSG_ARM_TAG_CPU_ARCH_PROFILE	"ARM_TAG_CPU_ARCH_PROFILE"
#define	MSG_ARM_TAG_CPU_ARCH_PROFILE_SIZE	24

#define	MSG_ARM_TAG_ARM_ISA_USE	"ARM_TAG_ARM_ISA_USE"
#define	MSG_ARM_TAG_ARM_ISA_USE_SIZE	19

#define	MSG_ARM_TAG_THUMB_ISA_USE	"ARM_TAG_THUMB_ISA_USE"
#define	MSG_ARM_TAG_THUMB_ISA_USE_SIZE	21

#define	MSG_ARM_TAG_FP_ARCH	"ARM_TAG_FP_ARCH"
#define	MSG_ARM_TAG_FP_ARCH_SIZE	15

#define	MSG_ARM_TAG_WWMX_ARCH	"ARM_TAG_WWMX_ARCH"
#define	MSG_ARM_TAG_WWMX_ARCH_SIZE	17

#define	MSG_ARM_TAG_ADVANCED_SIMD_ARCH	"ARM_TAG_ADVANCED_SIMD_ARCH"
#define	MSG_ARM_TAG_ADVANCED_SIMD_ARCH_SIZE	26

#define	MSG_ARM_TAG_ABI_PCS_CONFIG	"ARM_TAG_ABI_PCS_CONFIG"
#define	MSG_ARM_TAG_ABI_PCS_CONFIG_SIZE	22

#define	MSG_ARM_TAG_ABI_PCS_R9_USE	"ARM_TAG_ABI_PCS_R9_USE"
#define	MSG_ARM_TAG_ABI_PCS_R9_USE_SIZE	22

#define	MSG_ARM_TAG_ABI_PCS_RW_DATA	"ARM_TAG_ABI_PCS_RW_DATA"
#define	MSG_ARM_TAG_ABI_PCS_RW_DATA_SIZE	23

#define	MSG_ARM_TAG_ABI_PCS_RO_DATA	"ARM_TAG_ABI_PCS_RO_DATA"
#define	MSG_ARM_TAG_ABI_PCS_RO_DATA_SIZE	23

#define	MSG_ARM_TAG_ABI_PCS_GOT_USE	"ARM_TAG_ABI_PCS_GOT_USE"
#define	MSG_ARM_TAG_ABI_PCS_GOT_USE_SIZE	23

#define	MSG_ARM_TAG_ABI_PCS_WCHAR_T	"ARM_TAG_ABI_PCS_WCHAR_T"
#define	MSG_ARM_TAG_ABI_PCS_WCHAR_T_SIZE	23

#define	MSG_ARM_TAG_ABI_FP_ROUNDING	"ARM_TAG_ABI_FP_ROUNDING"
#define	MSG_ARM_TAG_ABI_FP_ROUNDING_SIZE	23

#define	MSG_ARM_TAG_ABI_FP_DENORMAL	"ARM_TAG_ABI_FP_DENORMAL"
#define	MSG_ARM_TAG_ABI_FP_DENORMAL_SIZE	23

#define	MSG_ARM_TAG_ABI_FP_EXCEPTIONS	"ARM_TAG_ABI_FP_EXCEPTIONS"
#define	MSG_ARM_TAG_ABI_FP_EXCEPTIONS_SIZE	25

#define	MSG_ARM_TAG_ABI_FP_USER_EXCEPTIONS	"ARM_TAG_ABI_FP_USER_EXCEPTIONS"
#define	MSG_ARM_TAG_ABI_FP_USER_EXCEPTIONS_SIZE	30

#define	MSG_ARM_TAG_ABI_FP_NUMBER_MODEL	"ARM_TAG_ABI_FP_NUMBER_MODEL"
#define	MSG_ARM_TAG_ABI_FP_NUMBER_MODEL_SIZE	27

#define	MSG_ARM_TAG_ABI_ALIGN_NEEDED	"ARM_TAG_ABI_ALIGN_NEEDED"
#define	MSG_ARM_TAG_ABI_ALIGN_NEEDED_SIZE	24

#define	MSG_ARM_TAG_ABI_ALIGN_PRESERVED	"ARM_TAG_ABI_ALIGN_PRESERVED"
#define	MSG_ARM_TAG_ABI_ALIGN_PRESERVED_SIZE	27

#define	MSG_ARM_TAG_ABI_ENUM_SIZE	"ARM_TAG_ABI_ENUM_SIZE"
#define	MSG_ARM_TAG_ABI_ENUM_SIZE_SIZE	21

#define	MSG_ARM_TAG_ABI_HARDFP_USE	"ARM_TAG_ABI_HARDFP_USE"
#define	MSG_ARM_TAG_ABI_HARDFP_USE_SIZE	22

#define	MSG_ARM_TAG_ABI_VFP_ARGS	"ARM_TAG_ABI_VFP_ARGS"
#define	MSG_ARM_TAG_ABI_VFP_ARGS_SIZE	20

#define	MSG_ARM_TAG_ABI_WMMX_ARGS	"ARM_TAG_ABI_WMMX_ARGS"
#define	MSG_ARM_TAG_ABI_WMMX_ARGS_SIZE	21

#define	MSG_ARM_TAG_ABI_OPTIMIZATION_GOALS	"ARM_TAG_ABI_OPTIMIZATION_GOALS"
#define	MSG_ARM_TAG_ABI_OPTIMIZATION_GOALS_SIZE	30

#define	MSG_ARM_TAG_ABI_FP_OPTIMIZATION_GOALS	"ARM_TAG_ABI_FP_OPTIMIZATION_GOALS"
#define	MSG_ARM_TAG_ABI_FP_OPTIMIZATION_GOALS_SIZE	33

#define	MSG_ARM_TAG_COMPATIBILITY	"ARM_TAG_COMPATIBILITY"
#define	MSG_ARM_TAG_COMPATIBILITY_SIZE	21

#define	MSG_ARM_TAG_UNALIGNED_ACCESS	"ARM_TAG_UNALIGNED_ACCESS"
#define	MSG_ARM_TAG_UNALIGNED_ACCESS_SIZE	24

#define	MSG_ARM_TAG_FP_HP_EXTENSION	"ARM_TAG_FP_HP_EXTENSION"
#define	MSG_ARM_TAG_FP_HP_EXTENSION_SIZE	23

#define	MSG_ARM_TAG_ABI_16BIT_FORMAT	"ARM_TAG_ABI_16BIT_FORMAT"
#define	MSG_ARM_TAG_ABI_16BIT_FORMAT_SIZE	24

#define	MSG_ARM_TAG_MPEXTENSION_USE	"ARM_TAG_MPEXTENSION_USE"
#define	MSG_ARM_TAG_MPEXTENSION_USE_SIZE	23

#define	MSG_ARM_TAG_DIV_USE	"ARM_TAG_DIV_USE"
#define	MSG_ARM_TAG_DIV_USE_SIZE	15

#define	MSG_ARM_TAG_NODEFAULTS	"ARM_TAG_NODEFAULTS"
#define	MSG_ARM_TAG_NODEFAULTS_SIZE	18

#define	MSG_ARM_TAG_ALSO_COMPATIBLE_WITH	"ARM_TAG_ALSO_COMPATIBLE_WITH"
#define	MSG_ARM_TAG_ALSO_COMPATIBLE_WITH_SIZE	28

#define	MSG_ARM_TAG_T2EE_USE	"ARM_TAG_T2EE_USE"
#define	MSG_ARM_TAG_T2EE_USE_SIZE	16

#define	MSG_ARM_TAG_CONFORMANCE	"ARM_TAG_CONFORMANCE"
#define	MSG_ARM_TAG_CONFORMANCE_SIZE	19

#define	MSG_ARM_TAG_VIRTUALIZATION_USE	"ARM_TAG_VIRTUALIZATION_USE"
#define	MSG_ARM_TAG_VIRTUALIZATION_USE_SIZE	26

#define	MSG_ARM_TAG_MPEXTENSION_USE_2	"ARM_TAG_MPEXTENSION_USE_2"
#define	MSG_ARM_TAG_MPEXTENSION_USE_2_SIZE	25

#endif	/* LINTSUP_SUPPRESS_STRINGS */

#endif	/* __lint */

#endif
