#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2013 (c) Joyent, Inc.  All rights reserved.
#

#
#	This Makefile defines the build rules for building inside of armv6 which
#	are shared across all of the boards.
#
$(OBJS_DIR)/%.o:		$(UTSBASE)/armv6/boot/%.c
	$(COMPILE.c) -o $@ $<

$(OBJS_DIR)/%.o:		$(UTSBASE)/armv6/math/%.c
	$(COMPILE.c) -o $@ $<

$(OBJS_DIR)/%.o:		$(UTSBASE)/armv6/math/%.s
	$(COMPILE.s) -o $@ $<

$(OBJS_DIR)/%.o:		$(UTSBASE)/armv6/misc/%.c
	$(COMPILE.c) -o $@ $<

$(OBJS_DIR)/%.o:		$(UTSBASE)/armv6/os/%.c
	$(COMPILE.c) -o $@ $<
